### ISSUE TITLE
执行run_client.sh出现无法访问的问题

### ISSUE THREAD

**Issue by huangfu001206** [trpc-group/trpc-cpp#130]
使用trpc生成桩代码，然后执行./run_client.sh出现了如下报错
Starting local Bazel server and connecting to it...
INFO: Repository trpc_cpp instantiated at:
  /home/huangfu/common/trpc-cpp/examples/try/forward/WORKSPACE:2:15: in <toplevel>
Repository rule git_repository defined at:
 /home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'trpc_cpp':
   Traceback (most recent call last):
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
                update = _clone_or_update_repo(ctx)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
                git_ = git_repo(ctx, directory)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 109, column 10, in _update
                fetch(ctx, git_repo)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 152, column 15, in fetch
                _error(ctx.name, ["git"] + args, st.stderr)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin master:origin/master' while working with @trpc_cpp:
fatal: 无法访问 'https://git.woa.com/trpc-cpp/open-source/trpc-cpp.git/'：The requested URL returned error: 403
ERROR: /home/huangfu/common/trpc-cpp/examples/try/forward/WORKSPACE:2:15: fetching git_repository rule //external:trpc_cpp: Traceback (most recent call last):
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
                update = _clone_or_update_repo(ctx)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
                git_ = git_repo(ctx, directory)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 109, column 10, in _update
                fetch(ctx, git_repo)
        File "/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 152, column 15, in fetch
                _error(ctx.name, ["git"] + args, st.stderr)
        File “/home/huangfu/.cache/bazel/_bazel_huangfu/895430b3b0095088170b48818227c861/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin master:origin/master' while working with @trpc_cpp:
fatal: 无法访问 'https://git.woa.com/trpc-cpp/open-source/trpc-cpp.git/'：The requested URL returned error: 403
ERROR: Error computing the main repository mapping: no such package '@trpc_cpp//trpc': error running 'git fetch origin master:origin/master' while working with @trpc_cpp:
fatal: 无法访问 'https://git.woa.com/trpc-cpp/open-source/trpc-cpp.git/'：The requested URL returned error: 403
Loading: 

然后，我访问了https://git.woa.com/trpc-cpp/open-source/trpc-cpp.git/ 这个网站，出现了如下图示，用微信扫码也无法访问。
![image](https://github.com/trpc-group/trpc-cpp/assets/65485301/0a9052a6-dc02-4163-b38a-a5a56bdd6c59)

本人为初学者，正在上手，麻烦您解答下，非常感谢！

**Comment by weimch** [comment]
把WORKSPACE文件里网址换成 https://github.com/trpc-group/trpc-cpp.git 再试试。

这个地址引用错误我们修复下。

**Comment by weimch** [comment]
> 把WORKSPACE文件里网址换成 https://github.com/trpc-group/trpc-cpp.git 再试试。
> 
> 这个地址引用错误我们修复下。

branch改成main

**Comment by huangfu001206** [comment]
非常感谢，按照上述步骤，已经执行成功了
